version: '3.1'

services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 8088:8080
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'yadda'
      MYSQL_DATABASE: 'monolithic'
    ports:
      - 3306:3306
